/**
 * @file tuya_config.h
 * @brief IoT specific configuration file
 *
 * @copyright Copyright (c) 2021-2024 Tuya Inc. All Rights Reserved.
 */

#ifndef TUYA_CONFIG_H_
#define TUYA_CONFIG_H_

/**
 * @brief configure the product information
 *
 * TUYA_PRODUCT_ID: PID, create on the Tuya IoT platform
 * TUYA_DEVICE_UUID: UUID, create on the Tuya IoT platform
 * TUYA_DEVICE_AUTHKEY: AUTHKEY, create on the Tuya IoT platform
 *
 * detail please refer to:
 * 1. Create the product and get the pid:
 * https://developer.tuya.com/cn/docs/iot-device-dev/application-creation?id=Kbxw7ket3aujc
 * 2. Get the open-sdk license code or module: https://platform.tuya.com/purchase/index?type=6
 *
 * warning: please replace these production information with your product id
 * and license, otherwise the demo cannot work.
 *
 */
// clang-format off

/**
 * Tuya credentials can be provided in 3 ways (in order of priority):
 * 1. CMake build flags: -DTUYA_PRODUCT_ID="xxx" -DTUYA_OPENSDK_UUID="xxx" -DTUYA_OPENSDK_AUTHKEY="xxx"
 * 2. Environment variables (via build script): TUYA_PRODUCT_ID, TUYA_OPENSDK_UUID, TUYA_OPENSDK_AUTHKEY  
 * 3. Hardcoded values below (NOT recommended for production)
 */

// Product ID - Check if defined via build system, otherwise use fallback
#ifndef TUYA_PRODUCT_ID
#define TUYA_PRODUCT_ID      "REPLACE_WITH_YOUR_PRODUCT_ID"
#endif

// UUID - Check if defined via build system, otherwise use fallback
#ifndef TUYA_OPENSDK_UUID
#define TUYA_OPENSDK_UUID    "REPLACE_WITH_YOUR_UUID"
#endif

// AuthKey - Check if defined via build system, otherwise use fallback
#ifndef TUYA_OPENSDK_AUTHKEY
#define TUYA_OPENSDK_AUTHKEY "REPLACE_WITH_YOUR_AUTHKEY"
#endif

/**
 * @brief PINCODE for AP provisioning
 * 
 * TUYA_NETCFG_PINCODE: a random PINCODE for AP provisioning, PINCODE was generated BY TUYA PMS system!!!
 * 
 * WARNING: PINCODE is mandatory for AP provisioning
 */
// #define TUYA_NETCFG_PINCODE   "69832860"

/**
 * @brief Skip Tuya Cloud Services
 * 
 * When set to 1, disables Tuya Cloud IoT features (Smart Life app, cloud DP sync).
 * This eliminates constant TLS connections that can block real-time UDP audio streaming.
 * 
 * Use this mode when:
 * - Only web app communication is needed (via TCP/UDP)
 * - Real-time audio/video streaming is critical
 * - You don't need Tuya Smart Life app integration
 * 
 * Set via environment variable: SKIP_TUYA_CLOUD="1"
 */
#ifndef SKIP_TUYA_CLOUD
#define SKIP_TUYA_CLOUD      0
#endif

// clang-format on

#endif
