/**
 * @file tuya_config.h
 * @brief IoT specific configuration file
 *
 * @copyright Copyright (c) 2021-2024 Tuya Inc. All Rights Reserved.
 */

#ifndef TUYA_CONFIG_H_
#define TUYA_CONFIG_H_

/**
 * @brief configure the product information
 *
 * TUYA_PRODUCT_ID: PID, create on the Tuya IoT platform
 * TUYA_DEVICE_UUID: UUID, create on the Tuya IoT platform
 * TUYA_DEVICE_AUTHKEY: AUTHKEY, create on the Tuya IoT platform
 *
 * detail please refer to:
 * 1. Create the product and get the pid:
 * https://developer.tuya.com/cn/docs/iot-device-dev/application-creation?id=Kbxw7ket3aujc
 * 2. Get the open-sdk license code or module: https://platform.tuya.com/purchase/index?type=6
 *
 * warning: please replace these production information with your product id
 * and license, otherwise the demo cannot work.
 *
 */
// clang-format off

/**
 * Tuya credentials can be provided in 3 ways (in order of priority):
 * 1. CMake build flags: -DTUYA_PRODUCT_ID="xxx" -DTUYA_OPENSDK_UUID="xxx" -DTUYA_OPENSDK_AUTHKEY="xxx"
 * 2. Environment variables (via build script): TUYA_PRODUCT_ID, TUYA_OPENSDK_UUID, TUYA_OPENSDK_AUTHKEY  
 * 3. Hardcoded values below (NOT recommended for production)
 */

// Product ID - Check if defined via build system, otherwise use fallback
#ifndef TUYA_PRODUCT_ID
#define TUYA_PRODUCT_ID      "REPLACE_WITH_YOUR_PRODUCT_ID"
#endif

// UUID - Check if defined via build system, otherwise use fallback
#ifndef TUYA_OPENSDK_UUID
#define TUYA_OPENSDK_UUID    "REPLACE_WITH_YOUR_UUID"
#endif

// AuthKey - Check if defined via build system, otherwise use fallback
#ifndef TUYA_OPENSDK_AUTHKEY
#define TUYA_OPENSDK_AUTHKEY "REPLACE_WITH_YOUR_AUTHKEY"
#endif

/**
 * @brief PINCODE for AP provisioning
 * 
 * TUYA_NETCFG_PINCODE: a random PINCODE for AP provisioning, PINCODE was generated BY TUYA PMS system!!!
 * 
 * WARNING: PINCODE is mandatory for AP provisioning
 */
// #define TUYA_NETCFG_PINCODE   "69832860"

/**
 * @brief RTSP Tunnel Configuration
 * 
 * These settings configure the RTSP tunnel that forwards local camera
 * streams to the VPS through the DevKit.
 * 
 * Environment variables (via build script):
 * - RTSP_CAMERA_HOST: Local RTSP camera IP (e.g., "192.168.1.100")
 * - RTSP_CAMERA_PORT: Camera RTSP port (default: 554)
 * - RTSP_VPS_HOST: VPS hostname/IP for tunnel endpoint
 * - RTSP_VPS_PORT: VPS port for RTSP tunnel (default: 8554)
 * - RTSP_TUNNEL_ENABLED: Set to "1" to enable tunnel on startup
 */

// RTSP Camera Configuration
#ifndef RTSP_CAMERA_HOST
#define RTSP_CAMERA_HOST     "192.168.1.100"
#endif

#ifndef RTSP_CAMERA_PORT
#define RTSP_CAMERA_PORT     554
#endif

// VPS Tunnel Endpoint
#ifndef RTSP_VPS_HOST
#define RTSP_VPS_HOST        "13.212.218.43"
#endif

#ifndef RTSP_VPS_PORT
#define RTSP_VPS_PORT        8554
#endif

// Auto-start tunnel on boot (set to 1 to enable)
#ifndef RTSP_TUNNEL_ENABLED
#define RTSP_TUNNEL_ENABLED  0
#endif

// clang-format on

#endif
